import {WeightDivision} from "../../champions/boxrec.champions.constants";
import {BoxrecRole} from "../../search/boxrec.search.constants";

export interface BoxrecLocationsPeopleParams {
    country?: Country;
    division?: WeightDivision;
    l_go?: any; // BoxRec param that doesn't do anything
    region?: string;
    role?: BoxrecRole;
    town?: string;
}

export interface BoxrecLocationsPeopleParamsTransformed {
    "l[country]"?: Country;
    "l[division]"?: WeightDivision;
    "l[region]"?: string;
    "l[role]"?: BoxrecRole;
    "l[town]"?: string;
    l_go?: any; // BoxRec param that doesn't do anything
    offset?: number;
}

// if needed to rebuild
// grab the dropdown HTML from the locations page
// run it through regexr with this regex `value\s?\=\s?\"(\w{1,2})\"\s?(?:selected\=\"selected\")?\>\s?([A-zÀ-ÿ\s’\-\(\)\.]+)`
// go to `list` and use this `"$2" = "$1",\n`
export enum Country {
    "Afghanistan" = "AF",
    "Albania" = "AL",
    "Algeria" = "DZ",
    "American Samoa" = "AS",
    "Andorra" = "AD",
    "Angola" = "AO",
    "Anguilla" = "AI",
    "Antarctica" = "AQ",
    "Antigua And Barbuda" = "AG",
    "Argentina" = "AR",
    "Armenia" = "AM",
    "Aruba" = "AW",
    "Australia" = "AU",
    "Austria" = "AT",
    "Azerbaijan" = "AZ",
    "Bahamas" = "BS",
    "Bahrain" = "BH",
    "Bangladesh" = "BD",
    "Barbados" = "BB",
    "Belarus" = "BY",
    "Belgium" = "BE",
    "Belize" = "BZ",
    "Benin" = "BJ",
    "Bermuda" = "BM",
    "Bhutan" = "BT",
    "Bolivia" = "BO",
    "Bonaire" = "BQ",
    "Bosnia And Herzegovina" = "BA",
    "Botswana" = "BW",
    "Bouvet Island" = "BV",
    "Brazil" = "BR",
    "British Indian Ocean Territory" = "IO",
    "British Virgin Islands" = "VG",
    "Brunei" = "BN",
    "Bulgaria" = "BG",
    "Burkina Faso" = "BF",
    "Burundi" = "BI",
    "Cambodia" = "KH",
    "Cameroon" = "CM",
    "Canada" = "CA",
    "Cape Verde" = "CV",
    "Cayman Islands" = "KY",
    "Central African Republic" = "CF",
    "Chad" = "TD",
    "Chile" = "CL",
    "China" = "CN",
    "Christmas Island" = "CX",
    "Cocos (Keeling) Islands" = "CC",
    "Colombia" = "CO",
    "Comoros" = "KM",
    "Congo" = "CG",
    "Cook Islands" = "CK",
    "Costa Rica" = "CR",
    "Croatia" = "HR",
    "Cuba" = "CU",
    "Curaçao" = "CW",
    "Cyprus" = "CY",
    "Czech Republic" = "CZ",
    "Côte D’Ivoire" = "CI",
    "Democratic Republic Of The Congo" = "CD",
    "Denmark" = "DK",
    "Djibouti" = "DJ",
    "Dominica" = "DM",
    "Dominican Republic" = "DO",
    "Ecuador" = "EC",
    "Egypt" = "EG",
    "El Salvador" = "SV",
    "Equatorial Guinea" = "GQ",
    "Eritrea" = "ER",
    "Estonia" = "EE",
    "Ethiopia" = "ET",
    "Falkland Islands" = "FK",
    "Faroe Islands" = "FO",
    "Fiji" = "FJ",
    "Finland" = "FI",
    "France" = "FR",
    "French Guiana" = "GF",
    "French Polynesia" = "PF",
    "French Southern Territories" = "TF",
    "Gabon" = "GA",
    "Gambia" = "GM",
    "Georgia" = "GE",
    "Germany" = "DE",
    "Ghana" = "GH",
    "Gibraltar" = "GI",
    "Greece" = "GR",
    "Greenland" = "GL",
    "Grenada" = "GD",
    "Guadeloupe" = "GP",
    "Guam" = "GU",
    "Guatemala" = "GT",
    "Guinea" = "GN",
    "Guinea-Bissau" = "GW",
    "Guyana" = "GY",
    "Haiti" = "HT",
    "Heard Island And Mcdonald Islands" = "HM",
    "Honduras" = "HN",
    "Hong Kong S.A.R." = "HK",
    "Hungary" = "HU",
    "Iceland" = "IS",
    "India" = "IN",
    "Indonesia" = "ID",
    "Iran" = "IR",
    "Iraq" = "IQ",
    "Ireland" = "IE",
    "Israel" = "IL",
    "Italy" = "IT",
    "Jamaica" = "JM",
    "Japan" = "JP",
    "Jordan" = "JO",
    "Kazakhstan" = "KZ",
    "Kenya" = "KE",
    "Kiribati" = "KI",
    "Kosovo" = "XK",
    "Kuwait" = "KW",
    "Kyrgyzstan" = "KG",
    "Laos" = "LA",
    "Latvia" = "LV",
    "Lebanon" = "LB",
    "Lesotho" = "LS",
    "Liberia" = "LR",
    "Libya" = "LY",
    "Liechtenstein" = "LI",
    "Lithuania" = "LT",
    "Luxembourg" = "LU",
    "Macao S.A.R." = "MO",
    "Macedonia" = "MK",
    "Madagascar" = "MG",
    "Malawi" = "MW",
    "Malaysia" = "MY",
    "Maldives" = "MV",
    "Mali" = "ML",
    "Malta" = "MT",
    "Marshall Islands" = "MH",
    "Martinique" = "MQ",
    "Mauritania" = "MR",
    "Mauritius" = "MU",
    "Mayotte" = "YT",
    "Mexico" = "MX",
    "Micronesia" = "FM",
    "Moldova" = "MD",
    "Monaco" = "MC",
    "Mongolia" = "MN",
    "Montenegro" = "ME",
    "Montserrat" = "MS",
    "Morocco" = "MA",
    "Mozambique" = "MZ",
    "Myanmar" = "MM",
    "Namibia" = "NA",
    "Nauru" = "NR",
    "Nepal" = "NP",
    "Netherlands" = "NL",
    "Netherlands Antilles" = "AN",
    "New Caledonia" = "NC",
    "New Zealand" = "NZ",
    "Nicaragua" = "NI",
    "Niger" = "NE",
    "Nigeria" = "NG",
    "Niue" = "NU",
    "Norfolk Island" = "NF",
    "North Korea" = "KP",
    "Northern Mariana Islands" = "MP",
    "Norway" = "NO",
    "Oman" = "OM",
    "Pakistan" = "PK",
    "Palau" = "PW",
    "Palestinian Territory" = "PS",
    "Panama" = "PA",
    "Papua New Guinea" = "PG",
    "Paraguay" = "PY",
    "Peru" = "PE",
    "Philippines" = "PH",
    "Pitcairn" = "PN",
    "Poland" = "PL",
    "Portugal" = "PT",
    "Puerto Rico" = "PR",
    "Qatar" = "QA",
    "Romania" = "RO",
    "Russia" = "RU",
    "Rwanda" = "RW",
    "Réunion" = "RE",
    "Saint Helena" = "SH",
    "Saint Kitts And Nevis" = "KN",
    "Saint Lucia" = "LC",
    "Saint Pierre And Miquelon" = "PM",
    "Saint Vincent And The Grenadines" = "VC",
    "Samoa" = "WS",
    "San Marino" = "SM",
    "Sao Tome And Principe" = "ST",
    "Saudi Arabia" = "SA",
    "Senegal" = "SN",
    "Serbia" = "RS",
    "Seychelles" = "SC",
    "Sierra Leone" = "SL",
    "Singapore" = "SG",
    "Sint Maarten" = "SX",
    "Slovakia" = "SK",
    "Slovenia" = "SI",
    "Solomon Islands" = "SB",
    "Somalia" = "SO",
    "South Africa" = "ZA",
    "South Georgia And The South Sandwich Islands" = "GS",
    "South Korea" = "KR",
    "South Sudan" = "SS",
    "Spain" = "ES",
    "Sri Lanka" = "LK",
    "Sudan" = "SD",
    "Suriname" = "SR",
    "Svalbard And Jan Mayen" = "SJ",
    "Swaziland" = "SZ",
    "Sweden" = "SE",
    "Switzerland" = "CH",
    "Syria" = "SY",
    "Taiwan" = "TW",
    "Tajikistan" = "TJ",
    "Tanzania" = "TZ",
    "Thailand" = "TH",
    "Timor-Leste" = "TL",
    "Togo" = "TG",
    "Tokelau" = "TK",
    "Tonga" = "TO",
    "Trinidad And Tobago" = "TT",
    "Tunisia" = "TN",
    "Turkey" = "TR",
    "Turkmenistan" = "TM",
    "Turks And Caicos Islands" = "TC",
    "Tuvalu" = "TV",
    "U.S. Virgin Islands" = "VI",
    "Uganda" = "UG",
    "Ukraine" = "UA",
    "United Arab Emirates" = "AE",
    "United Kingdom" = "UK",
    "United States Minor Outlying Islands" = "UM",
    "Uruguay" = "UY",
    "USA" = "US",
    "Uzbekistan" = "UZ",
    "Vanuatu" = "VU",
    "Vatican" = "VA",
    "Venezuela" = "VE",
    "Vietnam" = "VN",
    "Wallis And Futuna" = "WF",
    "Western Sahara" = "EH",
    "Yemen" = "YE",
    "Yugoslavia" = "YU",
    "Zambia" = "ZM",
    "Zimbabwe" = "ZW",
}
