version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 15 # follows the tslint.json param `cyclomatic-complexity`
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: 80 #language-specific defaults. overrides affect all languages.
  identical-code:
    enabled: true
    config:
      threshold: 80 #language-specific defaults. overrides affect all languages.
plugins:
 rubocop:
  enabled: true
 eslint:
  enabled: true
exclude_patterns:
- "config/"
- "db/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/*.spec.ts" # todo remove as it doesn't hurt to watch maintainability on spec files
- "**/test/"
- "**/tests/"
- "**/vendor/"
- "**/*.d.ts"
- "**/docs/" # ignore docs