version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.8
jobs:
  build:
    docker:
    - image: circleci/node:8.9.4
    steps: # a collection of executable commands
    - checkout # special step to check out source code to working directory
    - run:
        name: Update NPM
        command: 'sudo npm install -g npm@latest'
    - restore_cache: # special step to restore the dependency cache
        # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
        key: dependency-cache-{{ checksum "yarn.lock" }}
    - run:
        name: Install dependencies
        # use yarn install to ensure proper dependency caching
        command: yarn install
    - save_cache: # special step to save the dependency cache
        key: dependency-cache-{{ checksum "yarn.lock" }}
        paths:
        - ./node_modules
    - run:
        name: Run TSLint
        command: npm run tslint
    - run:
        name: Run tests
        command: yarn jest --ci --config=jest.config.json --coverage --runInBand && cat ./coverage/lcov.info | yarn coveralls
    - store_artifacts: # upload test coverage as artifact
        path: ./coverage/lcov-report
        prefix: tests
    - run:
        name: Generate docs
        command: npm run generate-docs
  push_to_s3:
    docker:
      - image: 'circleci/python:2.7'
    steps: # a collection of executable commands
    - checkout # special step to check out source code to working directory
    - run:
        command: mkdir bucket && echo "lorum ipsum" > bucket/build_asset.txt
    - aws-s3/sync:
        from: bucket
        to: 's3://boxrec-npm-docs/prefix'
        arguments: |
          --acl public-read \
          --cache-control "max-age=86400"
        overwrite: true
    - aws-s3/copy:
        from: bucket/build_asset.txt
        to: 's3://boxrec-npm-docs'
        arguments: '--dryrun'

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
              - master
              - develop
              #- /feature.*/ # todo uncomment
      - push_to_s3:
          # requires: build # todo uncomment
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
              - master
              - develop
              - /feature.*/ # todo shouldn't push to s3 when feature branch
