version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.8
jobs:
  # Build job that installs and saves cache
  build:
    docker:
    - image: cimg/node:17.4.0
    steps: # a collection of executable commands
    - checkout # special step to check out source code to working directory
    - restore_cache: # special step to restore the dependency cache
        # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
        key: dependency-cache-{{ checksum "yarn.lock" }}
    - run:
        name: Install dependencies
        # use yarn install to ensure proper dependency caching
        command: yarn install --frozen-lockfile
    - save_cache: # special step to save the dependency cache
        key: dependency-cache-{{ checksum "yarn.lock" }}
        paths:
        - ./node_modules
  # Checks out code and runs lint/tests
  # Does not require dependencies installed
  lint_and_test:
    docker:
    - image: cimg/node:17.4.0
    steps: # a collection of executable commands
    - checkout
    - restore_cache: # special step to restore the dependency cache
        # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
        key: dependency-cache-{{ checksum "yarn.lock" }}
    - run:
        name: Run TSLint
        command: npm run tslint
    - run:
        name: Run tests
        command: yarn jest --ci --config=jest.config.json --coverage --runInBand
    - run:
        name: Push results to Coveralls
        # Only push to Coveralls if we have the repo token
        # If the MR is a fork, Coveralls will reject and fail.  Therefore we skip this step
        command: |
          if [[ -v "${COVERALLS_REPO_TOKEN}" ]]; then
            cat ./coverage/lcov.info | yarn coveralls
          fi
    - run:
        name: Generate docs
        command: npm run generate-docs
    - persist_to_workspace:
        root: docs
        paths:
        - .
  # Pushes the docs directory to s3 under a subfolder by branch name
  # Requires docs directory to be persisted beforehand
  push_docs_to_s3:
    docker:
    - image: circleci/python:2.7
    steps: # a collection of executable commands
    - attach_workspace:
        at: tmp/docs
    - aws-s3/sync:
        from: tmp/docs
        to: 's3://boxrec-npm-docs/$CIRCLE_BRANCH'
        arguments: |
          --acl public-read \
          --cache-control "max-age=86400 --delete"
workflows:
  version: 2
  build_and_push_to_s3:
    jobs:
    - build:
        filters:
          branches:
            # For whatever reason if we want to skip builds
            ignore: /skip-build\/*/
    - lint_and_test:
        requires:
        - build
    # Only push master branches and nothing else because no docs are needed for other branches
    - push_docs_to_s3:
        requires:
        - build
        - lint_and_test
        filters:
          branches:
            only:
            - master
