version: 2
jobs:
  build:
    branches:
      only:
      - master
      - develop
      - /feature.*/
    docker:
    - image: circleci/node:8.9.4
    steps: # a collection of executable commands
    - checkout # special step to check out source code to working directory
    - run:
        name: Update NPM
        command: 'sudo npm install -g npm@latest'
    - restore_cache: # special step to restore the dependency cache
        # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
        key: dependency-cache-{{ checksum "yarn.lock" }}
    - run:
        name: Install dependencies
        # use yarn install to ensure proper dependency caching
        command: yarn install
    - save_cache: # special step to save the dependency cache
        key: dependency-cache-{{ checksum "yarn.lock" }}
        paths:
        - ./node_modules
    - run:
        name: Run TSLint
        command: npm run tslint
    - run:
        name: Run tests
        command: yarn jest --ci --config=jest.config.json --coverage --runInBand && cat ./coverage/lcov.info | yarn coveralls
    - store_artifacts: # upload test coverage as artifact
        path: ./coverage/lcov-report
        prefix: tests
    - run:
        name: Deploy branch to Heroku
        command: |
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git $CIRCLE_BRANCH