version: 2
jobs:
  build:
    branches:
      only:
      - master
      - develop
      - /feature.*/
    docker:
    - image: circleci/node:8.9.4
    steps: # a collection of executable commands
    - checkout # special step to check out source code to working directory
    - run:
        name: Update NPM
        command: 'sudo npm install -g npm@latest'
    - restore_cache: # special step to restore the dependency cache
        # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: install NPM
        command: npm install
    - run:
        name: Install JUnit coverage reporter
        command: npm install jest-junit -D
    - save_cache: # special step to save the dependency cache
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
        - ./node_modules
    - run:
        name: Run tests with JUnit as reporter
        command: yarn jest --ci --config=jest.config.json --coverage --runInBand --reporters=default --reporters=jest-junit
        environment:
          JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
    - store_artifacts: # special step to save test results as as artifact
        # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
        path: test/reports
        prefix: tests
    - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
        path: ./coverage/lcov.info
    - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
        path: ./coverage/lcov.info
    # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples